### ISSUE TITLE
`require': cannot load such file -- mapscript (LoadError)

### ISSUE THREAD

**Issue by acesuares** [sourcepole/ruby_mapscript#1]
Hi there, 

thanks for making this gem available. 
I am hitting this:

```
gems/ruby_mapscript-0.3.0/lib/mapscript/mapscript_extensions.rb:3:in `require': cannot load such file -- mapscript (LoadError)
```

Can't find a find a mapscript.rb file on the system

```
$ locate mapscript.rb
gems/ruby_mapscript-0.3.0/lib/ruby_mapscript.rb
```

**Comment by robertpyke** [comment]
My setup:
- **Rails**: 3.2.11.
- **Ruby**: 1.9.3p194.
- **OS**: Ubuntu 12.10

I was having the same problem you're having. I fixed it by running: 

```
sudo apt-get install libmapscript-ruby1.9.1
```

It should be noted that I'm using the ubuntugis-unstable stream (for PostGIS v2 support), which is where my libmapscript-ruby1.9.1 package was installed from. You can add the repository via the following command: 

```
sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
```

I haven't done any further testing with the gem yet, so if I hit any other issues with my install, I'll post a follow up comment.

**Comment by arvindvyas** [comment]
My setup
  rails 2.3.5
  ruby 1.9.3
  os ubuntu 12.04
   its giving me 

  cannot load such file -- mapscript

**Comment by acesuares** [comment]
I get this error: /usr/lib/ruby/1.9.1/x86_64-linux/mapscript.so: warning: rb_define_const: invalid name `**FUNCTION**' for constant

This is with Ubuntu Raring (13.04). Webbrick starts, but instead of a map I get the follwing error: 
allocator undefined for Mapscript::MapObj

When I 'upgrade' to ubuntugis-unstable, like @robertpyke mentioned, then I don't get the rb_define_const error, but the app crashes hard when it wants to draw a map.

**Comment by acesuares** [comment]
anyone?

**Comment by acesuares** [comment]
https://github.com/sourcepole/ruby_mapscript/pull/2

**Comment by thomasgwatson** [comment]
Does this gem work with Ruby 1.8.3
