### ISSUE TITLE
Where can we get the mapscript extension?

### ISSUE THREAD

**Issue by DouglasAllen** [sourcepole/ruby_mapscript#5]
I am able to get an extension for the debian system libs but I need one for rvm or rbenv. How may I build that? This may be a good project for the Ruby community. I have done some Ruby C extensions before. Where could we get the source code for mapscript to build a mapscript.so?

**Comment by pka** [comment]
This repo is Ruby-only. Your questions seems to be related to the C library. The main discussion channel for Mapscript are the Mapserver mailing lists: http://mapserver.org/community/lists.html
