### ISSUE TITLE
mapscript doesn't work with Ubuntu 14.04

### ISSUE THREAD

**Issue by siru88** [sourcepole/ruby_mapscript#6]
I am trying to implement [mapwarper ](https://github.com/timwaters/mapwarper)for my server. The service is installed however mapscript doesn't seems to be working. I get the below error.

```
LoadError (cannot load such file -- mapscript):
  app/controllers/maps_controller.rb:692:in `<class:MapsController>'
  app/controllers/maps_controller.rb:1:in `<top (required)>'
```

I have installed ruby_mapscript and also added the below line in mapwarper/lib/enum_fu/Rakefile file. However, I still get the same error.

`t.libs << '/usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/2.0.0'`

Any help would be greatly appreciated.

Attached is the screenshot of the error in the browser. 
![mapscript error](https://cloud.githubusercontent.com/assets/12696196/16608341/5a669c14-4368-11e6-9086-5facc5798656.JPG)

**Comment by joschne** [comment]
Same problem here. Did you find a solution?

**Comment by siru88** [comment]
@joschne  the issue was that I was trying to install it on a machine that had multiple other map softwares installed. Installing this package on fresh Ubuntu machine worked. May be you can try a fresh Ubuntu machine and it should work.

**Comment by acesuares** [comment]
Can be closed.

**Comment by acesuares** [comment]
Can be closed.
